package com.example.linecommunityjoiner

enum class CommunityScreenType {
    UNKNOWN,
    AGE_CONFIRM_DIALOG,
    APPROVAL_PENDING,
    GENERIC_BLOCKER_DIALOG,
    ACCOUNT_SUSPENDED,
    ALREADY_IN_COMMUNITY,
    COMMUNITY_HOME,
    ROOM_LIST,
    QUESTION,
    PROFILE,
    REMINDER,
    APPLICATION_SENT,
    PASSWORD_ENTRY,
    CHAT_ROOM
}
